import { X, Mail, Loader2, AlertCircle } from "lucide-react";
import { useState, useEffect } from "react";
import emailjs from "emailjs-com";
import { calcModule, calcFinal, getGrade } from "../utils/marks";

function buildReportHTML(scored, studentName, regNo) {
  const finals  = scored.map(s => calcFinal(calcModule(s.m1), calcModule(s.m2)));
  const avg     = finals.reduce((a, v) => a + v, 0) / finals.length;
  const og      = getGrade(avg);
  const dateStr = new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });

  const rows = scored.map((s, i) => {
    const f  = finals[i];
    const g  = getGrade(f);
    const m1 = calcModule(s.m1);
    const m2 = calcModule(s.m2);
    return `
      <tr>
        <td>${s.name || `Subject ${i + 1}`}</td>
        <td>${m1 !== null ? m1.toFixed(1) + "/60" : "—"}</td>
        <td>${m2 !== null ? m2.toFixed(1) + "/60" : "—"}</td>
        <td><b style="color:${g.color}">${f.toFixed(1)}/60</b></td>
        <td style="color:${g.color};font-weight:800">${g.grade}</td>
        <td>${g.label}</td>
      </tr>`;
  }).join("");

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width,initial-scale=1"/>
  <title>EvalPro Assessment Report — ${studentName || "Student"}</title>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700;800&display=swap');
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'DM Sans', sans-serif; background: #f6f6fb; color: #111; padding: 48px 40px; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .logo { display: flex; align-items: center; gap: 10px; margin-bottom: 20px; }
    .logo-badge { width: 40px; height: 40px; border-radius: 8px; background: #0f3a7d; display: flex; align-items: center; justify-content: center; color: #fff; font-weight: 800; font-size: 14px; }
    .vignan-badge { width: 32px; height: 32px; border-radius: 6px; background: linear-gradient(135deg,#ff6b35,#f7931e); display: flex; align-items: center; justify-content: center; color: #fff; font-weight: 900; font-size: 11px; margin-left: 8px; }
    .logo-text { font-size: 18px; font-weight: 800; color: #0f3a7d; }
    .logo-text span { color: #ff6b35; font-weight: 700; }
    .institution { font-size: 11px; font-weight: 600; color: #666; margin-left: 8px; }
    h1 { font-size: 26px; font-weight: 800; color: #0f3a7d; letter-spacing: -0.5px; margin-bottom: 8px; }
    .meta { display: flex; gap: 18px; flex-wrap: wrap; margin-bottom: 4px; }
    .meta-item { font-size: 13px; color: #555; }
    .meta-item b { color: #0f3a7d; font-weight: 700; }
    .divider { height: 2px; background: linear-gradient(90deg,#0f3a7d,#ff6b35,transparent); margin: 24px 0; border-radius: 2px; }
    table { border-collapse: collapse; width: 100%; margin-bottom: 28px; }
    th { background: linear-gradient(135deg, #0f3a7d, #1e5a9e); color: #fff; padding: 14px 16px; text-align: left; font-weight: 800; font-size: 13px; }
    td { padding: 12px 16px; border-bottom: 1px solid rgba(0,0,0,0.08); font-size: 12px; }
    tr:nth-child(odd) { background: #f9fafb; }
    .overall { background: rgba(15,58,125,0.08); padding: 16px; border-radius: 8px; border-left: 4px solid #0f3a7d; margin-bottom: 20px; }
    .overall-text { font-size: 18px; font-weight: 800; color: #0f3a7d; }
    .grade { font-size: 14px; font-weight: 800; margin-top: 4px; }
    footer { margin-top: 40px; font-size: 11px; color: #999; text-align: center; }
  </style>
</head>
<body>
  <div class="logo">
    <div class="logo-badge">EP</div>
    <div class="logo-text">EvalPro <span>Assessment</span></div>
    <div class="vignan-badge">V</div>
    <div class="institution">Vignan University</div>
  </div>
  <h1>Assessment Report</h1>
  <div class="meta">
    <div class="meta-item"><b>Student:</b> ${studentName || "—"}</div>
    <div class="meta-item"><b>Reg No:</b> ${regNo || "—"}</div>
    <div class="meta-item"><b>Date:</b> ${dateStr}</div>
  </div>
  <div class="divider"></div>
  <table>
    <thead><tr><th>Subject</th><th>Module 1</th><th>Module 2</th><th>Final</th><th>Grade</th><th>Label</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
  <div class="overall">
    <div class="overall-text">Overall Average: ${avg.toFixed(1)} / 60</div>
    <div class="grade" style="color:${og.color}">${og.grade} — ${og.label}</div>
  </div>
  <footer>Generated by EvalPro — Professional Assessment System</footer>
</body>
</html>`;
}

export default function EmailExportModal({ isOpen, onClose, studentName, regNo, subjects }) {
  if (!isOpen || !subjects.length) return null;

  const [email, setEmail] = useState("");
  const [loading, setLoading] = useState(false);
  const [message, setMessage] = useState(null);
  const scored = subjects.filter(s => s.m1 && (s.m1.pret || s.m1.t1 || s.m1.t2 || s.m1.t3 || s.m1.t4 || s.m1.t5));

  // Initialize EmailJS with your public key
  useEffect(() => {
    emailjs.init("eCVnfqhYSFtIS2GwU");
  }, []);

  const isValidEmail = /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);

  async function sendEmail() {
    if (!isValidEmail) {
      setMessage({ type: "error", text: "Please enter a valid email address" });
      return;
    }

    setLoading(true);
    setMessage(null);

    try {
      // Calculate finals and average
      const finals = scored.map(s => calcFinal(calcModule(s.m1), calcModule(s.m2)));
      const avg = finals.reduce((a, v) => a + v, 0) / finals.length;

      // Build subjects list with improvements
      const subjectsList = scored.map((s, i) => {
        const m1 = calcModule(s.m1);
        const m2 = calcModule(s.m2);
        const f = finals[i];
        const improvement = m2 > m1 ? "📈 Improved" : m2 < m1 ? "📉 Declined" : "➡️ Same";
        return `${s.name}: M1=${m1?.toFixed(1) || "—"}, M2=${m2?.toFixed(1) || "—"}, Avg=${f?.toFixed(1) || "—"} | ${improvement}`;
      }).join("\n");

      // Build HTML table for subjects_report (so HTML template can render it)
      // Email template expects `{{subjects_rows}}` inside its subject table.
      // We'll generate only the <tr> rows (not another full <table>), so it renders correctly.
      const subjects_rows = scored

        .map((s, i) => {
          const f = finals[i];
          const g = getGrade(f);
          const m1 = calcModule(s.m1);
          const m2 = calcModule(s.m2);

          const m1Txt = m1 !== null && m1 !== undefined ? m1.toFixed(1) : "—";
          const m2Txt = m2 !== null && m2 !== undefined ? m2.toFixed(1) : "—";

          const improvement = m2 > m1 ? "📈 Improved" : m2 < m1 ? "📉 Declined" : "➡️ Same";

          return `
            <tr>
              <td style="padding:8px; border:1px solid #ddd;">${s.name || `Subject ${i + 1}`}</td>
              <td style="padding:8px; border:1px solid #ddd;">M1=${m1Txt}</td>
              <td style="padding:8px; border:1px solid #ddd;">${m2Txt === "—" ? `M2=—` : `M2=${m2Txt}`}</td>
              <td style="padding:8px; border:1px solid #ddd;">Avg=${f.toFixed(1)}</td>
              <td style="padding:8px; border:1px solid #ddd;">${improvement}</td>
            </tr>
          `;
        })
        .join("");

      // Also provide plain-text version for templates that expect it (EMAIL_TEMPLATE_SETUP.md uses subjects_report)
      const subjects_report = scored
        .map((s, i) => {
          const m1 = calcModule(s.m1);
          const m2 = calcModule(s.m2);
          const f = finals[i];
          const improvement = m2 > m1 ? "📈 Improved" : m2 < m1 ? "📉 Declined" : "➡️ Same";
          return `${s.name}: M1=${m1?.toFixed(1) || "—"}, M2=${m2?.toFixed(1) || "—"}, Avg=${f?.toFixed(1) || "—"} | ${improvement}`;
        })
        .join("\n");

      // Simple email params (must match template variables in EmailJS)
      const emailParams = {
        email: email,
        to_email: email,
        to_name: studentName || "Student",
        student_name: studentName || "Student",
        reg_no: regNo || "—",
        overall_average: avg.toFixed(1),
        report_date: new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }),
        subjects_rows: subjects_rows,
        subjects_report: subjects_report,
      };

      console.log("📧 Sending email with EmailJS...", emailParams);

      // Send using EmailJS
      const result = await emailjs.send(
        "service_hnz9xcj",
        "template_fzocxnc",
        emailParams
      );

      console.log("✅ EmailJS Response:", result);

      if (result.status === 200) {
        setMessage({
          type: "success",
          text: `✓ Report sent to ${email}! Check your inbox.`
        });

        setTimeout(() => {
          setEmail("");
          onClose();
        }, 2500);
      }
    } catch (e) {
      console.error("❌ EmailJS Error:", e);

      setMessage({
        type: "error",
        text: `❌ Error: ${e.text || e.message || "Failed to send email"}`
      });
    } finally {
      setLoading(false);
    }
  }

  return (
    <div
      style={{
        position: "fixed",
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        background: "rgba(0,0,0,0.5)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 200,
        backdropFilter: "blur(4px)",
        overflow: "auto",
      }}
      onClick={onClose}
    >
      <div
        style={{
          background: "#fff",
          borderRadius: 14,
          padding: 32,
          maxWidth: 500,
          boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
          position: "relative",
          margin: 20,
        }}
        onClick={(e) => e.stopPropagation()}
      >
        {/* Close button */}
        <button
          onClick={onClose}
          style={{
            position: "absolute",
            top: 16,
            right: 16,
            background: "none",
            border: "none",
            cursor: "pointer",
            color: "#6b7280",
            padding: 8,
          }}
        >
          <X size={20} />
        </button>

        {/* Header */}
        <div style={{ marginBottom: 24, display: "flex", alignItems: "center", gap: 12 }}>
          <div
            style={{
              width: 48,
              height: 48,
              borderRadius: 10,
              background: "linear-gradient(135deg, #3b82f6, #1e40af)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
            }}
          >
            <Mail size={24} color="#fff" />
          </div>
          <div>
            <h3
              style={{
                margin: 0,
                fontSize: 22,
                fontWeight: 800,
                color: "#0f3a7d",
              }}
            >
              Email Report
            </h3>
            <p
              style={{
                margin: "4px 0 0 0",
                fontSize: 13,
                color: "#6b7280",
              }}
            >
              Send assessment report directly to email
            </p>
          </div>
        </div>

        {/* Student Info */}
        <div
          style={{
            background: "rgba(15,58,125,0.05)",
            border: "1px solid rgba(15,58,125,0.2)",
            borderRadius: 10,
            padding: 12,
            marginBottom: 20,
            fontSize: 13,
          }}
        >
          <div style={{ color: "#6b7280", marginBottom: 4 }}>
            <strong style={{ color: "#0f3a7d" }}>Student:</strong> {studentName || "—"}
          </div>
          <div style={{ color: "#6b7280" }}>
            <strong style={{ color: "#0f3a7d" }}>Reg No:</strong> {regNo || "—"}
          </div>
        </div>

        {/* Email Input */}
        <div style={{ marginBottom: 20 }}>
          <label
            style={{
              display: "block",
              fontSize: 13,
              fontWeight: 600,
              color: "#1f2937",
              marginBottom: 8,
            }}
          >
            Email Address <span style={{ color: "#dc2626" }}>*</span>
          </label>
          <input
            type="email"
            value={email}
            onChange={(e) => setEmail(e.target.value)}
            placeholder="student@example.com"
            disabled={loading}
            style={{
              width: "100%",
              padding: "10px 12px",
              border: `1.5px solid ${isValidEmail || !email ? "rgba(99,102,241,0.2)" : "rgba(220,38,38,0.3)"}`,
              borderRadius: 8,
              fontSize: 14,
              fontFamily: "inherit",
              background: "#f9fafb",
              color: "#1f2937",
              transition: "all 0.2s",
              boxSizing: "border-box",
            }}
          />
          {email && !isValidEmail && (
            <p style={{ fontSize: 12, color: "#dc2626", margin: "6px 0 0 0" }}>
              Please enter a valid email address
            </p>
          )}
        </div>

        {/* Message */}
        {message && (
          <div
            style={{
              background:
                message.type === "success"
                  ? "rgba(16,185,129,0.1)"
                  : "rgba(220,38,38,0.1)",
              border: `1px solid ${
                message.type === "success"
                  ? "rgba(16,185,129,0.3)"
                  : "rgba(220,38,38,0.3)"
              }`,
              borderRadius: 8,
              padding: 12,
              fontSize: 13,
              color:
                message.type === "success" ? "#059669" : "#dc2626",
              marginBottom: 16,
            }}
          >
            {message.text}
          </div>
        )}

        {/* Buttons */}
        <div style={{ display: "flex", gap: 12 }}>
          <button
            onClick={onClose}
            disabled={loading}
            style={{
              flex: 1,
              padding: "11px 16px",
              border: "1.5px solid rgba(99,102,241,0.2)",
              borderRadius: 8,
              background: "transparent",
              color: "#6366f1",
              fontSize: 13,
              fontWeight: 600,
              cursor: loading ? "not-allowed" : "pointer",
              fontFamily: "inherit",
              transition: "all 0.2s",
              opacity: loading ? 0.5 : 1,
            }}
          >
            Cancel
          </button>
          <button
            onClick={sendEmail}
            disabled={!isValidEmail || loading}
            style={{
              flex: 1,
              padding: "11px 16px",
              borderRadius: 8,
              background: isValidEmail && !loading ? "linear-gradient(135deg, #3b82f6, #1e40af)" : "#ccc",
              border: "none",
              color: "#fff",
              fontSize: 13,
              fontWeight: 600,
              cursor: isValidEmail && !loading ? "pointer" : "not-allowed",
              fontFamily: "inherit",
              transition: "all 0.2s",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              gap: 8,
            }}
          >
            {loading ? <Loader2 size={14} style={{ animation: "spin 1s linear infinite" }} /> : <Mail size={14} />}
            {loading ? "Sending..." : "Send Email"}
          </button>
        </div>

        {/* Setup Status - Hidden Credentials */}
        <div
          style={{
            marginTop: 16,
            padding: 14,
            background: "rgba(16,185,129,0.08)",
            border: "1px solid rgba(16,185,129,0.3)",
            borderRadius: 8,
            fontSize: 11,
            color: "#065f46",
            lineHeight: 1.7,
          }}
        >
          <strong style={{ display: "block", marginBottom: 6, color: "#059669" }}>✅ Email System Ready</strong>
          <div style={{ fontSize: 11, color: "#047857" }}>
            EmailJS is connected and ready to send reports to the specified email address.
          </div>
        </div>
      </div>
    </div>
  );
}
